# consolidate SEGM from conll:SEGM (< morph), or conll:TRANSLATION (< sux_projected)

PREFIX powla: <http://purl.org/powla/powla.owl#> 
PREFIX conll: <http://ufal.mff.cuni.cz/conll2009-st/task-description.html#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX terms: <http://purl.org/acoli/open-ie/> 
PREFIX x: <http://purl.org/acoli/conll-rdf/xml#> 
PREFIX nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# use _[GLOSS] if (unlikely multi-word SEGM or as fallback)
INSERT {
	?w conll:SEGM ?new
} WHERE {
	?w conll:TRANSLATION ?gloss.
	?w a nif:Word.
	MINUS { ?w conll:SEGM [] }
	BIND(concat("_[",replace(?gloss,"  *","."),"]") as ?new)
};

